<?php
    $scope = (isset($scope)) ? $scope : true;
?>
<div class="box each-post" id="each-post-<?php echo $post['id']?>">
    <?php $user = get_user($post['user_id']);?>
    <div class="head clearfix">
        <div class="float-left">
            <a tabindex="0" data-toggle="popover"
               data-trigger="hover"
               data-content="
               <?php echo view('main::user/popover', array('user' => $user))?>
               "
               data-placement="bottom"
               class="ajax-link m-popover <?php echo (selected_is_rtl()) ? 'float-left' : null?>" href="<?php echo profile_link($user)?>">
                <?php if(selected_is_rtl()):?>
                    <span><?php echo $user['full_name']?></span>
                <?php endif?>
                <img src="<?php echo get_avatar(75, $user)?>"/>
                <?php if(!selected_is_rtl()):?>
                    <span><?php echo $user['full_name']?> <?php echo view('main::user/badges', array('user' => $user))?>

                        <?php if(!$scope):$coin = get_coin($post['coin_id'])?>
                            <?php if($coin):?>
                                -
                                    <a href="<?php echo url('coin/'.strtolower($coin['symbol']))?>" class="ajax-link"><img src="<?php echo url($coin['logo_small'])?>" style="width: 15px;height: 15px"/><?php echo $coin['symbol']?></a>
                                <?php endif?>
                        <?php endif?> -
                    <a class="ajax-link" href="<?php echo url('post/'.$post['id'])?>"><span class="post-time" style="font-size: 11px;color: grey;font-weight: normal"><?php echo format_time($post['date_created'])?></span></a>
                    </span>

                <?php endif?>
            </a>
        </div>
        <div class="float-right dropdown">
            <?php echo view('main::post/menu', array('post' => $post))?>
        </div>
    </div>
   <div class="body">
       <div class="caption <?php echo (!$post['content']) ? 'hide' : null?>">
           <span class="caption-<?php echo $post['id']?>"><?php echo output_text($post['content'])?></span>
       </div>
       <?php $images = perfectUnserialize($post['images']); if($images): ?>
           <div class="post-images">
               <?php $i =0; foreach($images as $image):?>
                   <div class="image image-<?php echo $i?>">
                       <?php if(is_gif($image)):?>
                           <img style="width: 100%"   class="gif " src="<?php echo url(str_replace('gif', 'jpg', $image))?>"/>
                       <?php else:?>
                           <img  class="lozad" data-src="<?php echo url($image)?>"/>
                       <?php endif?>
                   </div>

               <?php $i++; endforeach?>
           </div>

       <?php endif?>
   </div>
    <div class="foot">
        <div class="post-like-container clearfix">
            <div class="float-left">
                <ul class="nav">
                    <li class="nav-item">
                        <a data-id="<?php echo $post['id']?>" class="nav-link active like-btn <?php echo has_liked($post['id'])? 'liked' : null?>" href="#"><i class="icons icon-like"></i></a>
                    </li>
                    <li class="nav-item">
                        <a data-id="<?php echo $post['id']?>" class="nav-link post-comment-btn" href="#"><i class="icons icon-bubble"></i></a>
                    </li>

                </ul>
            </div>
            <div class="float-right">
                <ul class="nav">
                    <li class="nav-item">
                        <span class="likes-count" style="font-weight: bold"><span class="likes-count-<?php echo $post['id']?>" ><?php echo count_likes($post['id'])?></span> <?php _lang('likes')?></span>
                    </li>
                </ul>
            </div>
        </div>



        <div class="comments">


                <div class="comment-form clearfix">

                    <div class="float-left">
                        <form data-id="<?php echo $post['id']?>" data-type="post" class="clearfix comment-form-<?php echo $post['id']?>" action="" method="post">
                            <input autocomplete="off" placeholder="<?php _lang('add-a-comment')?>" type="text" name="comment" class="form-control"/>
                        </form>
                    </div>


                </div>

            <?php if(count_comments($post['id']) > config('comment-per-page', 5)):?>
                <a class="load-more-comment" data-id="<?php echo $post['id']?>" data-offset="0" href="" style="display: block;margin: 10px 0"><?php _lang('load-more-comments')?></a>
            <?php endif?>
            <div class="comments-list comments-lists-<?php echo $post['id']?>">

                <?php foreach(array_reverse(get_comments($post['id'])) as $comment):?>
                    <?php echo view('main::post/comment', array('comment' => $comment))?>
                <?php endforeach?>
            </div>
        </div>
    </div>
</div>