
<?php $posts = get_posts(0, app()->profileId)?>
<?php if($posts):?>
<div id="post-lists" class=" post-list" data-userid="<?php echo app()->profileId?>"  data-offset="0">
    <?php foreach($posts as $post):?>
        <?php echo view('main::post/each', array('post' => $post, 'scope' => false));?>
    <?php endforeach?>
</div>
<?php else:?>
    <div style="text-align: center;padding: 40px  10px;font-size: 15px">
        <i class="icons icon-pie-chart" style="font-size: 50px;display: block;margin: 10px auto"></i>
        <?php _lang('no-posts-display')?>
    </div>
<?php endif?>