<div class="container">
    <?php $currency = getCurrencyDetail()?>
    <div class="profile-header">

        <div class="row">
            <div class="col-md-3">
                <div class="profile-avatar-container">
                    <div class="profile-avatar" style="background-image: url(<?php echo get_avatar(600,app()->profileUser)?>)"></div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="info">
                    <div class="clearfix">
                        <h1 class="float-left">
                            <?php echo app()->profileUser['full_name']?></h1>

                        <div class="float-right" style="">
                           <div style="margin:0 20px">
                               <?php if(config('show-point', true)):?>
                                   <span class="btn btn-sm btn-secondary" style="border-radius: 50px;display: inline-block;"> <?php echo app()->profileUser['point']?> <?php _lang('points')?> </span>
                               <?php endif?>
                           </div>
                        </div>
                    </div>
                    <div>


                    </div>
                    <div class="row coin-stat-info" style="padding: 0">
                        <div class="col-md-3">
                            <div class="stat">
                                <span class="title"><?php _lang('posts')?></span>
                                <span class="price" style="font-weight: 500"><?php echo count_posts(app()->profileUser['id'])?></span>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="stat">
                                <span class="title"><?php _lang('following')?></span>
                                <span class="price" style="font-weight: 500"> <?php echo count_follow(app()->profileUser['id'], true, 'coin')?> <span style="font-weight: normal;display: inline-block"><?php _lang('coins')?></span></span>
                            </div>
                        </div>


                    </div>

                </div>
                <ul class="menu">
                    <li><a href="" class=" ajax-link active" href=""><?php _lang('overview')?></a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <?php $badges = get_user_badges(app()->profileUser['id'])?>
            <?php if($badges):?>
                <div class="box">
                    <?php echo view('main::user/render-badges', array('user' => app()->profileUser))?>
                </div>
            <?php endif?>
            <?php if(app()->profileUser['bio']):?>
                <div class="box">
                    <div class="title"><?php _lang('about')?></div>
                    <?php echo app()->profileUser['bio']?>
                </div>
            <?php endif?>

            <?php if(app()->profileUser['website']):?>
                <div class="box">

                    <a href="<?php echo app()->profileUser['website']?>" onclick="window.open('<?php echo app()->profileUser['website']?>')"><?php echo app()->profileUser['website']?></a>
                </div>
            <?php endif?>

            <?php if(config('side_ads', false)):?>
                <div class="box">
                    <?php echo config('side_ads', '')?>
                </div>
            <?php endif?>
        </div>
        <div class="col-md-9">
            <?php echo $content?>
        </div>
    </div>
</div>

