<!DOCTYPE html>
    <html>

        <head>
            <style>
                body{
                    margin: 0;
                    padding: 0;
                    font-size: 15px;
                }
                .container{
                    max-width: 1000px;
                    margin: 20px auto;
                }
                table th, td{
                    padding: 10px 0;
                    text-align: left;
                    border-bottom: solid 1px #EAEAEA;
                }
                a {
                  color:#0066CC !important;;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h3>Sitemap for <?php echo url()?> | <a href="<?php echo url('sitemap/xml')?>">XML FORMAT</a> | <a href="<?php echo url('sitemap/txt')?>">TXT FORMAT</a></h3>
                <table>
                    <thead>
                    <tr>
                        <th style="width:80%">Page</th>
                        <th style="width:20%">Last Modified</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($links as $link):?>
                        <tr>
                            <td>
                                <a href="<?php echo $link['loc']?>"><?php echo $link['loc']?></a>
                            </td>
                            <td>
                                <?php echo $link['lastmod']?>
                            </td>
                        </tr>
                    <?php endforeach?>
                    </tbody>
                </table>
            </div>
        </body>
    </html>