<div class="container">

    <?php
    $privacy = ($type == 'mine') ? 0 : 1;
    $order = input('order', 'id');
    $offset = input('offset', 0);
    $lists = get_portfolios($privacy, $offset, $order);
    $baseLink = ($type == 'mine') ? url('portfolio/me') : url('portfolio/public');
        ?>

    <div class="box">
        <div class="row">
            <div class="col-md-9">
                <?php if($lists):?>
                    <div class="filter clearfix">
                        <div class="float-right">
                            <?php _lang('order-by')?>
                            <span class="btn-group">
                                <a href="<?php echo $baseLink?>?order=coins_count" class="btn btn-sm btn-secondary"><?php _lang('coins')?></a>
                                <a href="<?php echo $baseLink?>?order=views" class="btn btn-sm btn-secondary"><?php _lang('views')?></a>

                            </span>
                        </div>
                    </div>

                    <?php foreach($lists as $list):$user = get_user($list['user_id'])?>

                        <div class="each-forum clearfix">
                            <div class="float-left">
                                <img style="width: 25px;height: 25px;display: inline-block" src="<?php echo get_avatar(75, $user)?>"/>
                                <div style="display: inline-block">
                                    <a class="ajax-link" href="<?php echo portfolio_link($list)?>"><strong><?php echo $list['name']?></strong></a>
                                    <br/><span style="color: grey"><?php echo $user['full_name']?></span>
                                </div>
                            </div>
                            <div class="float-right">
                                <ul>

                                    <li>
                                        <span class="count"><?php echo $list['coins_count']?></span>
                                        <span><?php _lang('coins')?></span>
                                    </li>
                                    <li>
                                        <span class="count"><?php echo $list['views']?></span>
                                        <span><?php _lang('views')?></span>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    <?php endforeach?>


                        <div class="" style="text-align: center;display: block;padding-top: 30px">
                                <span class="btn-group">
                                    <?php

                                    $limit = 50;
                                    $previousOffset = ($offset == 0) ? 0 : $offset - $limit;
                                    $nextoffset = $offset + $limit;
                                    ?>
                                    <a href="<?php echo url($baseLink)?>?order=<?php echo $order?>&offset=<?php echo $previousOffset?>" class="btn btn-sm btn-secondary ajax-link" <?php echo ($offset== 0) ? 'disabled' : null?>><?php _lang('previous')?></a>
                                    <a href="<?php echo url($baseLink)?>?order=<?php echo $order?>&offset=<?php echo $nextoffset?>" class="btn btn-sm btn-secondary ajax-link"><?php _lang('next')?></a>
                                </span>
                        </div>

                <?php else:?>
                    <div id="empty-post-content" style="text-align: center;padding: 40px  10px;font-size: 15px">
                        <i class="icons icon-pie-chart" style="font-size: 50px;display: block;margin: 10px auto"></i>
                        <?php _lang('no-portfolio-yet')?>

                        <br/><br/><p><button class="btn btn-lg btn-secondary" data-toggle="modal" data-target="#portfolioModal"><?php _lang('start-a-portfolio')?></button></p>
                    </div>
                <?php endif?>
            </div>
            <div class="col-md-3">
                <div class="box side-box">
                    <div class="title"><?php _lang('top-trending-coin')?></div>
                    <?php foreach(get_top_coins() as $coin):?>
                        <div class="media user-inline">

                            <img style="width: 40px;height: 40px;border-radius: 100px" class="d-flex mr-3" src="<?php echo url($coin['logo'])?>" >
                            <div class="media-body">
                                <a style="display: block" class="ajax-link" href="<?php echo url('coin/'.strtolower($coin['symbol']).'/forum')?>">
                                    <h6 class="mt-0" style="font-size: 13px"><strong>
                                            <?php echo $coin['symbol']?></strong>
                                    </h6>
                                </a>
                            </div>

                            <div class="action">
                                <i class="icons icon-bubbles"></i> <?php echo $coin['post_count']?>
                            </div>
                        </div>
                    <?php endforeach?>
                </div>

                <?php if(config('show-top-members', true)):?>
                    <div class="box side-box">
                        <div class="title"><?php _lang('top-members')?></div>
                        <div class="content">
                            <?php foreach(get_top_members() as $user):?>
                                <a style="display: inline-block;margin: 2px" href="<?php echo profile_link($user)?>" class="tool-tip ajax-link" title="<?php echo $user['username']?> : <?php echo $user['point']?> <?php _lang('points')?>">
                                    <img style="width: 40px;height: 40px;border-radius: 100px" class="d-flex mr-3" src="<?php echo get_avatar(75, $user)?>" >
                                </a>
                            <?php endforeach?>
                        </div>
                    </div>
                <?php endif?>

                <?php if(config('side_ads', false)):?>
                    <div class="box">
                        <?php echo config('side_ads', '')?>
                    </div>
                <?php endif?>
            </div>
        </div>
    </div>
</div>