<?php echo view('main::post/editor', array('id' => $coin['id'], 'type' => 'coin'))?>

<div id="posts-list" data-userid="" data-page="coin|<?php echo $coin['id']?>" data-types="list" data-offset="0" class="post-list">
    <?php $posts = get_posts(0, null, 'coin|'.$coin['id'])?>
    <?php if($posts):?>
        <?php $i = 0; foreach($posts as $post):?>
            <?php echo view('main::post/each', array('post' => $post, 'scope' => true));?>

        <?php endforeach?>
    <?php else:?>
        <div id="empty-post-content" style="text-align: center;padding: 40px  10px;font-size: 15px">
            <i class="icons icon-pie-chart" style="font-size: 50px;display: block;margin: 10px auto"></i>
            <?php _lang('no-posts-display')?>
        </div>
    <?php endif?>


</div>