<div class="box" style="padding: 0;overflow: hidden">
    <table style="width: 100% !important;" id="exchangeDataTableList" data-coin="<?php echo $coin['symbol']?>"  class="table table-hover  table-coin">
        <thead>
        <tr>
            <th><?php _lang('market')?></th>
            <th><?php _lang('price')?></th>
            <th><?php _lang('open-24h')?></th>
            <th><?php _lang('range-24h')?></th>
            <th><?php _lang('volume-24h')?></th>
            <th><?php _lang('change-24h')?></th>
            <th><?php _lang('action')?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach(get_available_exchanges() as $exchange):?>
            <tr class="coin-exchange-container" id="<?php echo $exchange?>-detail-container" data-name="<?php echo $exchange?>" data-symbol="<?php echo $coin?>">
                <td>

                    <div class="name"><?php _lang('market')?> </div>
                    <div class="info" style="position: relative">
                        <span class="badge badge-default"><?php echo $exchange?></span>
                    </div>
                </td>
                <td>
                    <div class="name"><?php _lang('price')?> </div>
                    <div class="info" style="position: relative">
                        <sup style="position: absolute;top: 4px;left: -15px"><?php echo getCurrencySymbol()?></sup>
                        <span class="exchange-price"></span>
                    </div>
                </td>
                <td>
                    <div class="name"><?php _lang('open-24h')?> </div>
                    <div class="info" style="position: relative">
                        <sup style="position: absolute;top: 4px;left: -15px"><?php echo getCurrencySymbol()?></sup>
                        <span class="exchange-open"></span>
                    </div>
                </td>
                <td>
                    <div class="name"><?php _lang('range-24h')?> </div>
                    <div class="info" style="position: relative">
                        <div style="position: relative">

                            L :<?php echo getCurrencySymbol()?> <span class="exchange-low"></span>
                        </div>
                        <div style="position: relative">

                            H : <?php echo getCurrencySymbol()?> <span class="exchange-high"></span>
                        </div>

                    </div>
                </td>
                <td>
                    <div class="name"><?php _lang('volume-24h')?> </div>
                    <div class="info" style="position: relative">
                        <sup style="position: absolute;top: 4px;left: -15px"><?php echo getCurrencySymbol()?></sup>
                        <span class="exchange-volume"></span>
                    </div>
                </td>

                <td>
                    <div class="name"><?php _lang('change-24h')?> </div>
                    <div class="info" style="position: relative">
                        <span class="exchange-change"></span>
                    </div>
                </td>
                <td>
                    <a href="#" <?php echo (!$link) ? 'disabled' : null?> class="btn btn-sm  <?php echo (!$link) ? 'disabled btn-secondary' : 'btn-yellow'?>" style="padding: 5px;border-radius:4px;" onclick="return window.open('<?php echo $link?>')"><?php _lang('start-trading')?></a>
                </td>
            </tr>
        <?php endforeach?>
        </tbody>
    </table>
</div>