<div class="box" style="padding: 0">
    <table id="tradeDataTableList" data-coin="<?php echo $coin['symbol']?>"  class="table table-hover  table-coin">
        <thead>
        <tr>
            <th><?php _lang('market')?></th>
            <th><?php _lang('type')?></th>
            <th><?php _lang('price')?></th>
            <th><?php _lang('quantity')?></th>
            <th><?php _lang('total')?></th>

        </tr>
        </thead>
        <tbody id="trades">

        </tbody>

    </table>
</div>