<div class="clearfix">
    <div class="float-left">
        <h5><?php _lang('blog-manager')?>
            <button data-toggle="modal"data-target="#addBlogModal" class="btn btn-primary btn-sm"><?php _lang('add-blog')?></button>
        </h5>
    </div>
    <div class="float-right">
        <form action="" method="get">
            <input name="term" value="<?php echo input('term')?>" type="text" class="form-control-sm" placeholder="<?php _lang('search-coin')?>"/>
            <button class="btn btn-sm btn-primary"><i class="icons icon-magnifier"></i></button>
        </form>

    </div>
</div>
<div class="modal fade" id="addBlogModal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?php _lang('add-blog')?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form action=""  enctype="multipart/form-data" method="post">
                <input type="hidden" name="add_blog" value="1"/>
               <div class="modal-body">
                   <div class="form-group">
                       <label><?php _lang('title')?></label>
                       <input required type="text" class="form-control" name="title"/>
                   </div>

                   <div class="form-group">
                       <label><?php _lang('description')?></label>
                       <input required type="text" class="form-control" name="description"/>
                   </div>

                   <div class="form-group">
                       <label><?php _lang('image')?></label>
                       <input type="file" class="form-control" name="image"/>
                   </div>

                   <div class="form-group">
                       <label><?php _lang('content')?></label>
                       <textarea id="editor" required rows="10" name="content" class="form-control"></textarea>
                   </div>
               </div>

                <div class="modal-footer">

                    <button  class="btn btn-primary btn-sm"><?php _lang('save')?></button>
                </div>
            </form>

        </div>

    </div>
</div>

<table class="table table-hover table-striped">
    <thead>
    <tr>

        <th> <?php _lang('title')?> </th>
        <th><?php _lang('views')?></th>
        <th><?php _lang('unique-views')?></th>

        <th><a ><?php _lang('action')?></a></th>

    </tr>
    </thead>
    <tbody>
        <?php foreach($blogs as $blog):?>
            <tr>
                <td><a href="<?php echo blog_url($blog)?>"><?php echo $blog['title']?></a></td>
                <td><span class="badge badge-default"><?php echo $blog['views']?></span></td>
                <td><span class="badge badge-success"><?php echo unique_views('blog', $blog['id'])?></span></td>
                <td>
                    <div class="btn-group">
                        <a href="" data-toggle="modal" data-target="#<?php echo $blog['id']?>editBlogModal" class="btn btn-sm btn-secondary"><i class="icons icon-pencil"></i></a>
                        <a href="<?php echo url('admincp/blog/?action=delete&id='.$blog['id'])?>" class="btn btn-sm btn-secondary confirm-link"><i class="icons icon-close"></i></a>
                    </div>
                    <div class="modal fade" id="<?php echo $blog['id']?>editBlogModal">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title"><?php _lang('add-blog')?></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                <form action=""  enctype="multipart/form-data" method="post">
                                    <input type="hidden" name="edit_blog" value="<?php echo $blog['id']?>"/>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label><?php _lang('title')?></label>
                                            <input required type="text" value="<?php echo $blog['title']?>" class="form-control" name="title"/>
                                        </div>

                                        <div class="form-group">
                                            <label><?php _lang('description')?></label>
                                            <input value="<?php echo $blog['description']?>" required type="text" class="form-control" name="description"/>
                                        </div>

                                        <div class="form-group">
                                            <label><?php _lang('image')?></label>
                                            <input type="file" class="form-control" name="image"/>
                                        </div>

                                        <div class="form-group">
                                            <label><?php _lang('content')?></label>
                                            <textarea required rows="10" name="content" class="form-control"><?php echo $blog['content']?></textarea>
                                        </div>
                                    </div>

                                    <div class="modal-footer">

                                        <button  class="btn btn-primary btn-sm"><?php _lang('save')?></button>
                                    </div>
                                </form>

                            </div>

                        </div>
                    </div>
                </td>
            </tr>
        <?php endforeach?>
    </tbody>
</table>

<div class="" style="text-align: center">
            <span class="btn-group">
                <?php
                $offset = input('offset', 0);
                $previousOffset = ($offset == 0) ? 0 : $offset - 50;
                $nextoffset = $offset + 50;
                ?>
                <a href="<?php echo url('admincp/blog')?>?offset=<?php echo $previousOffset?>&term=<?php echo input('term')?>" class="btn btn-sm btn-secondary ajax-link" <?php echo ($offset== 0) ? 'disabled' : null?>><?php _lang('previous')?></a>
                <a href="<?php echo url('admincp/blog')?>?offset=<?php echo $nextoffset?>&term=<?php echo input('term')?>" class="btn btn-sm btn-secondary ajax-link"><?php _lang('next')?></a>
            </span>
</div>
