<div class="title"><?php _lang('dashboard')?></div>
<div class="row">
   <div class="col-sm-12 ">
       <div class="row">
           <div class="col-sm-4">
               <div class="stat row">
                   <div class="col-sm-4">
                       <i class="icons icon-user"></i>
                   </div>
                   <div class="col-sm-6">
                       <div class="count"><?php echo count_users()?></div>
                       <div class="text"><?php _lang('users')?></div>
                   </div>
               </div>
           </div>
           <div class="col-sm-4">
               <div class="stat row" style="background:#99CC00">
                   <div class="col-sm-4" style="background: #BCDD57">
                       <i class="icons icon-disc"></i>
                   </div>
                   <div class="col-sm-6" >
                       <div class="count"><?php echo count_all_coins()?></div>
                       <div class="text"><?php _lang('coins')?></div>
                   </div>
               </div>
           </div>
           <div class="col-sm-4">
               <div class="stat row" style="background:#9900CC">
                   <div class="col-sm-4" style="background: #B84FDC">
                       <i class="icons icon-bubble"></i>
                   </div>
                   <div class="col-sm-6" >
                       <div class="count"><?php echo count_all_comments()?></div>
                       <div class="text"><?php _lang('comments')?></div>
                   </div>
               </div>
           </div>
           <div class="col-sm-4">
               <div class="stat row" style="background: #FF0099">
                   <div class="col-sm-4" style="background: #FF57BC">
                       <i class="icons icon-heart"></i>
                   </div>
                   <div class="col-sm-6">
                       <div class="count"><?php echo count_all_likes()?></div>
                       <div class="text"><?php _lang('likes')?></div>
                   </div>
               </div>

           </div>
           <div class="col-sm-4">
               <div class="stat row" style="background: #2AA7D1">
                   <div class="col-sm-4" style="background: #72C5E1">
                       <i class="icons icon-bubbles"></i>
                   </div>
                   <div class="col-sm-6">
                       <div class="count"><?php echo count_all_posts()?></div>
                       <div class="text"><?php _lang('posts')?></div>
                   </div>
               </div>
           </div>
       </div>
   </div>

    <div class="col-sm-12" id="site-overview-chart">
        <script>
        function get_site_chart_config() {
                var config = {
            type: 'bar',
            data: {
                datasets: [{
                 			data: [
                 			<?php echo count_users()?>,
                 			 <?php echo count_all_comments()?>,
                 			 <?php echo count_all_likes()?>,
                 			 <?php echo count_all_posts()?>,
                 			 <?php echo count_all_coins()?>
                 			 ],
                 			backgroundColor: [
                 				"#FF8060",
                 				'#B84FDC',
                 				'#FF57BC',
                 				'#72C5E1',
                 				'#BCDD57'
                 			]
                 		}],

                 		labels: [
                        			"<?php _lang('users')?>",
                        			"<?php _lang('comments')?>",
                        			"<?php _lang('likes')?>",
                        			"<?php _lang('posts')?>",
                        			"<?php _lang('coins')?>"
                        		]
            },
            options: {
                responsive: true,
                legend: {
                    position: 'bottom',
                    display:false
                },
                title: {
                    display: true
                },
                animation: {
                    animateScale: true,
                    animateRotate: true
                }
            }};

            return config;
            }


            </script>
        <canvas width="400" height="400" style="width: 250px !important;height: 250px !important;"  id="site-overview-doughnut" class="" />
    </div>

</div>