<div style="margin: 20px">
    <div class="clearfix">
        <div class="float-left">
            <h5><?php _lang('menu-manager')?></h5>
        </div>
        <div class="float-right">
            <a href="" data-toggle="modal" data-target="#addMenuModal" class="btn btn-primary btn-sm"><?php _lang('add-new-menu')?></a>
        </div>
    </div>

    <hr/>
    <div class="modal fade" id="addMenuModal">
        <div class="modal-dialog " role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"><?php _lang('add-new-page')?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <form action=""  enctype="multipart/form-data" method="post">
                    <input type="hidden" name="add-menu" value="1"/>
                    <div class="modal-body">
                        <div class="form-group">
                            <label><?php _lang('title')?></label>
                            <input required type="text" class="form-control" name="title"/>
                        </div>

                        <div class="form-group">
                            <label><?php _lang('link')?></label>
                            <input required type="text"  class="form-control" name="link"/>
                        </div>

                        <div class="form-group">
                            <label><?php _lang('icon')?></label>
                            <input  type="text" class="form-control" name="icon"/>
                            <small>Only icons here are accepted <a href="#" onclick="return window.open('http://simplelineicons.com/')">http://simplelineicons.com/</a></small>
                        </div>

                        <div class="form-group">
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" checked name="ajaxify" value="1" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description"><?php _lang('ajaxify')?></span>
                            </label>
                        </div>


                        <div class="form-group">
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" checked name="new_tab" value="1" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description"><?php _lang('open-new-tab')?></span>
                            </label>
                        </div>

                        <div class="form-group">
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox"  name="visible" value="1" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description"><?php _lang('visible-in-main-menu')?></span>
                            </label>
                        </div>

                    </div>

                    <div class="modal-footer">

                        <button  class="btn btn-primary btn-sm"><?php _lang('save')?></button>
                    </div>
                </form>

            </div>

        </div>
    </div>

    <h4><?php _lang('main-menu')?></h4>
    <form action="" method="post">
        <div class="alert alert-info"><?php _lang('main-menu-info')?></div>
        <input type="hidden" name="static" value="1"/>
        <div class="form-group">
            <label class="custom-control custom-checkbox">
                <input <?php echo (config('market-menu', 1)) ? 'checked' : null?> type="checkbox"  name="val[market-menu]" value="1" class="custom-control-input">
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description"><?php _lang('market')?></span>
            </label>
        </div>
        <hr/>

        <div class="form-group">
            <label class="custom-control custom-checkbox">
                <input <?php echo (config('exchanges-menu', 1)) ? 'checked' : null?> type="checkbox"  name="val[exchanges-menu]" value="1" class="custom-control-input">
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description"><?php _lang('exchanges')?></span>
            </label>
        </div>
        <hr/>

        <div class="form-group">
            <label class="custom-control custom-checkbox">
                <input <?php echo (config('blog-menu', 1)) ? 'checked' : null?> type="checkbox"  name="val[blog-menu]" value="1" class="custom-control-input">
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description"><?php _lang('blog')?></span>
            </label>
        </div>
        <hr/>

        <div class="form-group">
            <label class="custom-control custom-checkbox">
                <input <?php echo (config('forum-menu', 1)) ? 'checked' : null?> type="checkbox"  name="val[forum-menu]" value="1" class="custom-control-input">
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description"><?php _lang('forum')?></span>
            </label>
        </div>
        <hr/>

        <div class="form-group">
            <label class="custom-control custom-checkbox">
                <input <?php echo (config('portfolio-menu', 1)) ? 'checked' : null?> type="checkbox"  name="val[portfolio-menu]" value="1" class="custom-control-input">
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description"><?php _lang('portfolio')?></span>
            </label>
        </div>
        <hr/>

        <button class="btn btn-sm btn-secondary"><?php _lang('save')?></button>
    </form>


    <h4><?php _lang('menu-list')?></h4>

    <table class="table ">
        <thead>
        <tr>
            <th style="width: 40%"><?php _lang('title')?></th>
            <th style="width: 40%"><?php _lang('link')?></th>
            <th><?php _lang('action')?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach(get_menu_list() as $menu):?>
            <tr>
                <td><?php echo $menu['title']?></td>
                <td><?php echo $menu['link']?></td>
                <td>
                    <div class="btn-group">
                        <a data-toggle="modal" data-target="#<?php echo $menu['id']?>editMenuModal" href="" class="btn btn-secondary"><i class="icons icon-pencil"></i></a>
                        <a href="<?php echo url('admincp/menus/?action=delete&id='.$menu['id'])?>" class="btn btn-secondary confirm-link"><i class="icons icon-close"></i></a>
                    </div>

                    <div class="modal fade" id="<?php echo $menu['id']?>editMenuModal">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title"><?php _lang('edit-menu')?></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                <form action=""  enctype="multipart/form-data" method="post">
                                    <input type="hidden" name="edit-menu" value="<?php echo $menu['id']?>"/>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label><?php _lang('title')?></label>
                                            <input required type="text" value="<?php echo $menu['title']?>" class="form-control" name="title"/>
                                        </div>

                                        <div class="form-group">
                                            <label><?php _lang('link')?></label>
                                            <input required type="text" value="<?php echo $menu['link']?>" class="form-control" name="link"/>
                                        </div>

                                        <div class="form-group">
                                            <label><?php _lang('icon')?></label>
                                            <input  value="<?php echo $menu['icon']?>" type="text" class="form-control" name="icon"/>
                                            <small>Only icons here are accepted <a href="#" onclick="return window.open('http://simplelineicons.com/')">http://simplelineicons.com/</a></small>
                                        </div>

                                        <div class="form-group">
                                            <label class="custom-control custom-checkbox">
                                                <input  type="checkbox" <?php echo ($menu['ajaxify']) ? 'checked' : null?> name="ajaxify" value="1" class="custom-control-input">
                                                <span class="custom-control-indicator"></span>
                                                <span class="custom-control-description"><?php _lang('ajaxify')?></span>
                                            </label>
                                        </div>


                                        <div class="form-group">
                                            <label class="custom-control custom-checkbox">
                                                <input <?php echo ($menu['new_tab']) ? 'checked' : null?> type="checkbox" checked name="new_tab" value="1" class="custom-control-input">
                                                <span class="custom-control-indicator"></span>
                                                <span class="custom-control-description"><?php _lang('open-new-tab')?></span>
                                            </label>
                                        </div>

                                        <div class="form-group">
                                            <label class="custom-control custom-checkbox">
                                                <input <?php echo ($menu['visible']) ? 'checked' : null?> type="checkbox"  name="visible" value="1" class="custom-control-input">
                                                <span class="custom-control-indicator"></span>
                                                <span class="custom-control-description"><?php _lang('visible-in-main-menu')?></span>
                                            </label>
                                        </div>
                                    </div>

                                    <div class="modal-footer">

                                        <button  class="btn btn-primary btn-sm"><?php _lang('save')?></button>
                                    </div>
                                </form>

                            </div>

                        </div>
                    </div>
                </td>
            </tr>
        <?php endforeach?>
        </tbody>

    </table>
</div>